// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AllTypeSelect: typeof import('./../components/content/allTypeSelect/allTypeSelect.vue')['default']
    BroadcastItem: typeof import('./../components/content/broadcastItem/broadcastItem.vue')['default']
    Carousel: typeof import('./../components/common/carousel/carousel.vue')['default']
    CommentList: typeof import('./../components/content/commentList/commentList.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    InfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    Lottie: typeof import('./../components/common/lottie/lottie.vue')['default']
    MvList: typeof import('./../components/content/mvList/mvList.vue')['default']
    MvListItem: typeof import('./../components/content/mvListItem/mvListItem.vue')['default']
    MvRanking: typeof import('./../components/content/mvRanking/mvRanking.vue')['default']
    NavBar: typeof import('./../components/common/navBar/navBar.vue')['default']
    PlyrVideo: typeof import('./../components/content/plyrVideo/plyrVideo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendComment: typeof import('./../components/content/sendComment/sendComment.vue')['default']
    TypeSelect: typeof import('./../components/content/typeSelect/typeSelect.vue')['default']
  }
}

export {}
