// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Carousel: typeof import('./../components/common/carousel/carousel.vue')['default']
    CommentList: typeof import('./../components/content/commentList/commentList.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    Lottie: typeof import('./../components/common/lottie/lottie.vue')['default']
    MvListItem: typeof import('./../components/content/mvListItem/mvListItem.vue')['default']
    MvRanking: typeof import('./../components/content/mvRanking/mvRanking.vue')['default']
    NavBar: typeof import('./../components/common/navBar/navBar.vue')['default']
    PlyrVideo: typeof import('./../components/common/plyrVideo/plyrVideo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendComment: typeof import('./../components/content/sendComment/sendComment.vue')['default']
    TypeSelect: typeof import('./../components/content/typeSelect/typeSelect.vue')['default']
  }
}

export {}
